### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by svycka** [bitnami/bitnami-docker-apache#21] opened 2015-12-01 10:58 UTC
config:
```yml
apache:
    image: bitnami/apache
    ports:
        - 80:80
    volumes:
        - .:/app
        - ./vhosts:/bitnami/apache/conf/vhosts
        - ./logs:/bitnami/apache/logs
```
response:
> Forbidden
>
> You don't have permission to access / on this server.
> Server unable to read htaccess file, denying access to be safe

how can I fix this?

**Comment by sameersbn** [comment] 2015-12-01 13:34
can you share the vhost configs in `vhosts/`?

**Comment by svycka** [comment] 2015-12-01 13:39
there nothing fancy:
```
<VirtualHost *:80>
    ServerAdmin admin@server
    DocumentRoot /app
    ServerName application.local
    ServerAlias www.application.local
    #ErrorLog ${APACHE_LOG_DIR}/error.log
    #CustomLog ${APACHE_LOG_DIR}/access.log combined
    <Directory "/app">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```
I guess problem is /app folder permissions but container does not let me change them, not sure why

**Comment by svycka** [comment] 2015-12-01 13:47
also I have tried this from example:
```
docker run --name apache -v /path/to/app:/app bitnami/apache
```
also same problem occurred without vhosts. and it seams that /app folder does not have correct permissions, but for example /logs are writable and I can see logs being written

**Comment by sameersbn** [comment] 2015-12-01 14:06
I tried the following for the test, and had no problems.

p.s. I had to add `127.0.0.1 application.local` in the `/etc/hosts` of my host.

```bash
mkdir apache_test
cd apache_test

cat > index.html <<EOF
<h1>hello</h1>
EOF

mkdir -p logs vhosts
cat > vhosts/app.conf  <<EOF
<VirtualHost *:80>
    ServerAdmin admin@server
    DocumentRoot /app
    ServerName application.local
    ServerAlias www.application.local
    #ErrorLog ${APACHE_LOG_DIR}/error.log
    #CustomLog ${APACHE_LOG_DIR}/access.log combined
    <Directory "/app">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF

cat > docker-compose.yml <<EOF
apache:
    image: bitnami/apache
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./vhosts:/bitnami/apache/conf/vhosts
      - ./logs:/bitnami/apache/logs
EOF

docker-compose up
```

Can you try the same? If you can alter the above command sequence to reproduce the issue, it would be great.

**Comment by svycka** [comment] 2015-12-01 14:16
that is what I did but I tried this one more time. First removed all containers and images to be sure that it is not cache problem but got same problem.
error_log:
```
[Tue Dec 01 14:09:52.425123 2015] [ssl:warn] [pid 170:tid 140126286985024] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 01 14:09:52.456078 2015] [ssl:warn] [pid 170:tid 140126286985024] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Dec 01 14:09:52.456441 2015] [lbmethod_heartbeat:notice] [pid 170:tid 140126286985024] AH02282: No slotmem from mod_heartmonitor
[Tue Dec 01 14:09:52.466254 2015] [mpm_event:notice] [pid 170:tid 140126286985024] AH00489: Apache/2.4.17 (Unix) OpenSSL/1.0.1p configured -- resuming normal operations
[Tue Dec 01 14:09:52.466361 2015] [core:notice] [pid 170:tid 140126286985024] AH00094: Command line: '/opt/bitnami/apache2/bin/httpd.bin -D FOREGROUND -f /opt/bitnami/apache2/conf/httpd.conf'
[Tue Dec 01 14:10:01.764015 2015] [core:crit] [pid 178:tid 140126073059072] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
[Tue Dec 01 14:10:03.858020 2015] [core:crit] [pid 178:tid 140125992384256] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
[Tue Dec 01 14:10:04.251457 2015] [core:crit] [pid 178:tid 140125983991552] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
[Tue Dec 01 14:10:04.469888 2015] [core:crit] [pid 178:tid 140125975598848] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
[Tue Dec 01 14:10:04.665133 2015] [core:crit] [pid 178:tid 140125967206144] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
[Tue Dec 01 14:10:04.847758 2015] [core:crit] [pid 178:tid 140125958813440] (13)Permission denied: [client 172.17.0.1:55296] AH00529: /app/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/app/' is executable
```
access_log:
```
172.17.0.1 - - [01/Dec/2015:14:10:01 +0000] "GET / HTTP/1.1" 403 271
172.17.0.1 - - [01/Dec/2015:14:10:03 +0000] "GET / HTTP/1.1" 403 271
172.17.0.1 - - [01/Dec/2015:14:10:04 +0000] "GET / HTTP/1.1" 403 271
172.17.0.1 - - [01/Dec/2015:14:10:04 +0000] "GET / HTTP/1.1" 403 271
172.17.0.1 - - [01/Dec/2015:14:10:04 +0000] "GET / HTTP/1.1" 403 271
172.17.0.1 - - [01/Dec/2015:14:10:04 +0000] "GET / HTTP/1.1" 403 271
```
files permissions:
```
$ docker exec b9022 ls -al /app/
total 5
drwx------  1 bitnami bitnami  464 Dec  1 14:08 .
drwxr-xr-x 17 root    root    4096 Dec  1 14:09 ..
-rw-------  1 bitnami bitnami  170 Dec  1 14:08 docker-compose.yml
-rw-------  1 bitnami bitnami   15 Dec  1 14:08 index.html
drwx------  1 bitnami bitnami  472 Dec  1 14:13 logs
drwx------  1 bitnami bitnami  152 Nov 25 04:47 vhosts
```

**Comment by sameersbn** [comment] 2015-12-01 14:27
I think you may have an older version  of `bitnami/apache` image cause in my case:

```bash
# docker exec -it apachetest_apache_1 ls -la /app/
total 24
drwxrwxr-x  4 daemon daemon 4096 Dec  1 14:24 .
drwxr-xr-x 17 root   root   4096 Dec  1 14:24 ..
-rw-rw-r--  1 daemon daemon  170 Dec  1 14:24 docker-compose.yml
-rw-rw-r--  1 daemon daemon   15 Dec  1 14:24 index.html
drwxrwxr-x  3 daemon daemon 4096 Dec  1 14:24 logs
drwxr-xr-x  2 daemon daemon 4096 Dec  1 07:50 vhosts
```

can you do `docker pull bitnami/apache:latest` before retrying?

**Comment by svycka** [comment] 2015-12-01 14:30
I think I found problem I am doing this on mounted ntfs partition and I guess this is the problem. I just tied this on my home folder and everything works just fine. but still I would like to do this on another partition because I do all projects there. Is there any way to solve this?
For example this one works: https://www.jverdeyen.be/docker/how-php-symfony-coreos-docker/ just copy paste docker-compose.yml and docker-compose up but this is with ngnix

**Comment by svycka** [comment] 2015-12-01 14:33
also you used a litle bit different cmd. With your cmd I get
```
$ docker exec -it apachetest_apache_1 ls -la /app/
total 24
drwxrwxr-x  4 daemon daemon 4096 Dec  1 14:19 .
drwxr-xr-x 18 root   root   4096 Dec  1 14:20 ..
-rw-rw-r--  1 daemon daemon  170 Dec  1 14:19 docker-compose.yml
-rw-rw-r--  1 daemon daemon   15 Dec  1 14:19 index.html
drwxrwxr-x  3 daemon daemon 4096 Dec  1 14:20 logs
drwxr-xr-x  2 daemon daemon 4096 Nov 25 04:47 vhosts
```

**Comment by svycka** [comment] 2015-12-01 14:36
ops sorry this is on my home folder not on mounted one that's why permissions are different

**Comment by sameersbn** [comment] 2015-12-01 14:40
> also you used a litle bit different cmd

different command in what sense?

Are you able to access the server now?

**Comment by svycka** [comment] 2015-12-01 14:42
the command does not matter sorry.
Yes and no :)

I can access it if i create project on my ubuntu partition in home folder, but on my mounted partition where I keep all projects I still can't make it work

**Comment by sameersbn** [comment] 2015-12-01 14:48
okay.. in that case it might have something to do with the mount points of the NTFS volume. In my case if i launch the above command sequence on a NTFS mounted volume it works. 

```bash
# docker exec -it apachetest_apache_1 ls -la /app/
total 5
drwxrwxrwx  1 root root  464 Dec  1 14:45 .
drwxr-xr-x 18 root root 4096 Dec  1 14:45 ..
-rwxrwxrwx  1 root root  170 Dec  1 14:45 docker-compose.yml
-rwxrwxrwx  1 root root   15 Dec  1 14:45 index.html
drwxrwxrwx  1 root root  472 Dec  1 14:45 logs
drwxrwxrwx  1 root root  152 Dec  1 07:50 vhosts
```

FWIW, I have the following in my `fstab`

```
UUID=0C795AC243E98ED8                     /media/myntfs    ntfs    defaults                  1       2
```

**Comment by svycka** [comment] 2015-12-01 14:58
I don't have  this partition in my fstab I mounted it in my ubuntu by clicking on the partition in nautilus but `mount` shows this:
```
/dev/sdb2 on /media/vytautas/D type fuseblk (rw,nosuid,nodev,allow_other,default_permissions,blksize=4096)
```
I guess it is mounted with default options no?

**Comment by sameersbn** [comment] 2015-12-01 15:17
when mounted by the file manager it mount point has different permissions than when mounted using fstab. I can see the issue you reported when i use a ntfs partition that is mounted by the file manager.

if this is a permanent disk attached to the system then you can mount it from the fstab, else you would need to unmount the partition and remount it using ntfs-ng.

**Comment by svycka** [comment] 2015-12-01 15:25
I see your point maybe I will try to add to fstab and test, but I wonder why this  https://www.jverdeyen.be/docker/how-php-symfony-coreos-docker/ example works.

**Comment by sameersbn** [comment] 2015-12-01 15:34
maybe because its using a data-only volume. i cannot confirm though

**Comment by prydonius** [comment] 2015-12-01 18:01
Could the example you linked to have worked because they're using nginx instead of apache? Have you tried with the [bitnami/nginx](/bitnami/bitnami-docker-nginx) container instead?

**Comment by svycka** [comment] 2015-12-02 09:10
ok adding to fstab fixed my issue and no I haven't tried nginx, but remember I had same problem with vagrant and nginx. Unfotunelty cant test it anymore.

**Comment by prydonius** [comment] 2015-12-02 20:28
Glad it's working for you now :). If you have any other issues with this, feel free to reopen or create a new issue. Thanks!

**Comment by svycka** [comment] 2015-12-03 08:24
@prydonius just for curiosity tried https://github.com/bitnami/bitnami-docker-nginx but also does not work

**Comment by sameersbn** [comment] 2015-12-03 10:50
I see the same behaviour as seen in apache. i.e. no problems when NTFS volume is mounted from fstab and permission issue when NTFS volume is mounted by the file manager. Also checked if using a data-only volume makes any difference.. it does not :)

**Comment by sameersbn** [comment] 2015-12-03 10:51
here is my test using nginx

```bash
mkdir nginx_test
cd nginx_test

cat > index.html <<EOF
<h1>hello</h1>
EOF

mkdir -p logs vhosts
cat > vhosts/app.conf  <<EOF
server {
    listen 0.0.0.0:80;
    server_name application.local;
    root /app;
    location / {
        index index.html;
    }
}
EOF

cat > docker-compose.yml <<EOF
nginx:
    image: bitnami/nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./vhosts:/bitnami/nginx/conf/vhosts
      - ./logs:/bitnami/nginx/logs
EOF

docker-compose up
```

**Comment by svycka** [comment] 2015-12-03 11:25
just copy paste and got this:
```
2015/12/03 11:09:26 [error] 177#0: *1 "/app/index.html" is forbidden (13: Permission denied), client: 172.17.0.1, server: application.local, request: "GET / HTTP/1.1", host: "application.local"
```

**Comment by svycka** [comment] 2015-12-03 11:34
I am on ubuntu 14.04, and have two hdd one is ssd with ubuntu instaled and other is with two partitions one with windows and one for storing data both are ntfs. don't know if this helps. I use this data partition from both windows and ubuntu. I think the problem is not this image but how I mount this data partition. Just don't know why configuration I mentioned earlier works and this image does not. Linux has way too many problems mounting ntfs partitions :D

**Comment by luismiguelprs** [comment] 2016-02-24 23:49
do you have a solution?

**Comment by svycka** [comment] 2016-02-25 07:27
nop

**Comment by luislobo** [comment] 2016-05-19 20:28
@sameersbn I've run your test, and this is what I get:
```
lobo@nbk-lobo-04-11 ~/tmp/nginx_test                                                                                                                            ⌚ 17:27:50
$ ll                                                                                                                                                             ⬡ 4.4.2 
total 16
-rw-rw-r-- 1 daemon daemon  166 may 19 17:27 docker-compose.yml
-rw-rw-r-- 1 daemon daemon   15 may 19 17:27 index.html
drwxrwxr-x 2 daemon daemon 4096 may 19 17:27 logs
drwxr-xr-x 2 daemon daemon 4096 abr 22 10:22 vhosts
```
All files have been changed to daemon daemon locally.
Is this a normal behavior of Bitnami images?
Change the user to that one?

**Comment by luislobo** [comment] 2016-05-27 23:57
This commit should fix your issues. It now just changes the group, not the user.
https://github.com/bitnami/bitnami-docker-apache/commit/6360ba94786dc8af404ac0b6e0c22a12e3f8e494

**Comment by prydonius** [comment] 2016-05-28 00:12
Thanks @luislobo, just released `bitnami/apache:2.4.20-r0` and `bitnami/apache:latest` that includes the changes you mentioned!

Let us know if the new version solves this issue

**Comment by luislobo** [comment] 2016-05-28 00:21
thanks! I'll do it. Also have bitnami/nginx and bitnami/php-fpm similar fixes, as I've been using those for other projects. I can test those too.

**Comment by prydonius** [comment] 2016-09-22 17:19
Closing, please reopen if issues persist.

**Closed by prydonius** 2016-09-22 17:19 UTC
